paderbox/io/audioread.py
Adds .m4a to supported filetypes of pb.audioread by exchanging SoundFile with audioread for .m4a files.
=> Audioread Fallback for .m4a files

paderbox/io/audioread.py, tests/io_tests/test_dump_load_audio.py
Fixes audioread for data of type BytesIO and adds test case for this error
=> Fixing load_audio dtype BytesIO

paderbox/utils/pandas_utils.py
Add support for non identifier column names:
- Old: When a column had a non identifier column name (e.g. whitespace in the name) py_query failed
- New: The column entry can be accessed with the `kwargs` dict (see doctest)
Add globals dict:
- The globals dict for the query was not accessible. Now the user can influence the globals dict and `setup_code` is no longer nessesary.
- example for using a numpy function in the query: `py_query(..., globals={'np': np})` 
Add option return_selection:
- Allow to return the selection indices instead of `data[return_selection]`
=> py_query: support non identifier column names, add globals dict and add return_selection

paderbox/io/audioread.py, paderbox/io/new_subdir.py, paderbox/utils/mapping.py, paderbox/utils/pretty.py, tests/io_tests/test_new_sub_dir.py
Changes:
- Rename get_new_folder to get_new_subdir
- Add prefix and suffix and remove try_id
- Add cli
- Add id_naming option
The first three commits are minor changes.
The discussion for this functions started in https://github.com/fgnt/padertorch/pull/46
=> Move get_new_subdir from padertorch to paderbox

paderbox/transform/module_stft.py
`_samples_to_stft_frames` used `math.ceil`. Using instead `//` allows the input arguments to be `int` and `np.array`.
Forward the num_samples argument in the STFT class for the inverse calculation
=> stft: remove ceil from _samples_to_stft_frames and add num_samples argument to stft

paderbox/utils/nested.py
The previous version of `nested_merge` didn't work with `collections.defaultdict` (and similar), because its internal state was not copied. Now, the function should work with any mapping type.
=> Make nested_merge work with any mapping

paderbox/array/interval/core.py
Previously, `ArrayInterval.sum` was broken for emtpy intervals (`len(interval.intervals) == 0`) and when `interval.inverse_mode = True`. I'm not a 100% sure if `self.shape[0]` is correct.
=> Fix ArrayInterval.sum if emtpy or inverse_mode=True

paderbox/array/interval/core.py
Enables easily saving ArrayIntervals to and loading them from .json files
=> Allow export of ArrayIntervals as tuple

paderbox/io/new_subdir.py, paderbox/utils/functional.py, tests/io_tests/test_new_sub_dir.py
`partial_decorator` allows calling a function multiple times to get a behavior similar to `functools.partial` (See doctests for examples).
Points that might need discussion:
- Naming of the decorator
- Naming of the file (`pb.utils.functional`) and potential imports on higher levels
- Naming of the `nested` argument and its default value
- `TypeErrors` for unexpected arguments don't contain the function name (because `inspect.Signature.bind` doesn't add it to the exception message)
=> Add partial_decorator

paderbox/utils/functional.py
Previously, with `**kwargs`, the wrapped function would get a `kwargs` argument, and with `*args` it would get an `args` argument. Now it is properly unpacked.
This was caused by `inspect.Signature.bind` to construct the arguments differently than I expected. Now the pure python unpacking is used.
=> Fix partial_decorator for kwargs

paderbox/array/interval/core.py
Previously, `ArrayInterval.__reduce__` ignored `inverse_mode`.
=> Fix ArrayInterval.__reduce__ for inverse mode

paderbox/array/__init__.py, paderbox/array/interval/__init__.py, paderbox/array/interval/core.py, tests/array_tests/test_array_interval.py
Before, it was possible to do
```python
ai = zeros('a')
```
without an exception. Now it raises an exception and also checks the shape on assignment like `ai.shape = (1, 2, 3, 4)`.
=> Normalize and validate shape of ArrayInterval while setting it

.github/workflows/wheels_windows.yml, maintenance.md, tests/io_tests/test_audiowrite.py
Adds github workflow generating wheels for Windows.
The pipeline can be triggered via the github UI ('workflow_dispatch') or is automatically started on version tags or branches.
Wheels are created for 32 and 64 bit Windows and for Python 3.6, 3.7, 3.8 and 3.9
For wheels created by the workflow see: https://github.com/alexanderwerning/paderbox/actions/runs/1887543159
=> Add workflow for Windows wheels

paderbox/array/interval/rttm.py, paderbox/io/cache_loader.py, paderbox/io/wrapper_dump.py, paderbox/io/wrapper_load.py, paderbox/utils/profiling.py
- load: Add support for .wav.gz and file descriptor
- dump: support flac, flac.gz and wav.gz
- lazy import pycallgraph
- Fix to_rttm_str: remove "same speaker" overlap
- cache_loader.check: Add keepfree_gigabytes option
=> Small fixes and improvements

.github/workflows/tests.yml, .github/workflows/tests_windows.yml, paderbox/io/atomic.py, paderbox/io/cache_loader.py, setup.py
- Allow a reuse
- Atomic file operations (avoid raise conditions across processes)
- Option to disable caching, i.e. change a flag instead of rewrite the code
- Fallback to no caching, when not enough space left.
- Add recursive load
=> DiskCacheLoader: Allow a cache reuse and use atomic file operations

paderbox/io/audioread.py, paderbox/io/wrapper_load.py
Add notation to select channels and a slice from the audio path passed to `load_audio`
=> Allow slicing notation in audio file names

paderbox/visualization/context_manager.py
In order to fix an error in the LaTeX-Export notebook, i got the error that the method pprint_val was not found. It seems to be no longer present in ScalarFormatter class of newer matplotlib versions and could possibly be replaced with format_data_short to achieve the result.
=> Replace deprecated pprint_val in context_manager.py

paderbox/utils/pandas_utils.py
in is_valid_variable_name because of exception when column name included a new line
=> Update pandas_utils.py for column names with line breaks

paderbox/transform/module_mfcc.py, tests/transform_tests/test_stft.py
In version 1.13.0, scipy removed the ability to import window functions from the signal namespace (see https://github.com/scipy/scipy/pull/19676). Window functions such as `hamming` have now to be imported from `scipy.signal.windows`.
scipy 1.13.0 release notes: https://scipy.github.io/devdocs/release/1.13.0-notes.html#pull-requests-for-1-13-0
=> Fix window function imports from scipy.signal

paderbox/visualization/plot.py
Proposal to fix deprecated code to run on python 3.11
=> fixed deprecated bug python 3.11 - np.int to int

.github/workflows/tests.yml, jenkins_common.bash, paderbox/array/interval/rttm.py, paderbox/io/wrapper_load.py
PyTorch 2.6 changed `weights_only` from `False` to `True` and forgot to support `numpy`.
- apply https://github.com/fgnt/padertorch/pull/163 to `pb.io.load`
- pth supports now unsafe=False via `torch.load(..., weights_only=True)`
- Note: For `unsafe=False` to be safe needs at least torch 2.6. Earlier versions have bugs, see e.g. https://github.com/pytorch/pytorch/issues/152006
- support .yml as alternative to .yaml
=> Add support for pytorch 2.6 in pb.io.load for pth files
